name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - uses: actions/checkout@v4
    #   with:
    #     repository: 'sa-concept-refactoring/llvm-project'
    #     ref: 'inline-concept-requirement'
    #     path: first-refactoring-source-code
    #     sparse-checkout: |
    #       clang-tools-extra/clangd/refactor/tweaks/InlineConceptRequirement.cpp
    #       clang-tools-extra/clangd/unittests/tweaks/InlineConceptRequirementTests.cpp
    # - uses: actions/checkout@v4
    #   with:
    #     repository: 'sa-concept-refactoring/llvm-project'
    #     ref: 'abbreviate-function-template'
    #     path: second-refactoring-source-code
    #     sparse-checkout: |
    #       clang-tools-extra/clangd/refactor/tweaks/AbbreviateFunctionTemplate.cpp
    #       clang-tools-extra/clangd/unittests/tweaks/AbbreviateFunctionTemplateTests.cpp
    # - uses: actions/checkout@v4
    #   with:
    #     repository: 'sa-concept-refactoring/test-project'
    #     path: test-project-source-code
    # - run: sed -i 's|// \#showSourceFile|\#showSourceFile|' main.typ
    - uses: DeterminateSystems/nix-installer-action@v6
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: mkdir out
    - run: nix run github:typst/typst/v0.10.0 -- compile main.typ out/main.pdf
    - uses: actions/upload-pages-artifact@v1
      with: { path: 'out' }

  Deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: Build
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
